// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/evmts/codex/codex-go/internal/client (interfaces: Client,HTTPClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_client.go -package=mocks github.com/evmts/codex/codex-go/internal/client Client,HTTPClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	client "github.com/evmts/codex/codex-go/internal/client"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Complete mocks base method.
func (m *MockClient) Complete(ctx context.Context, req *client.ChatCompletionRequest) (*client.ChatCompletionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, req)
	ret0, _ := ret[0].(*client.ChatCompletionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Complete indicates an expected call of Complete.
func (mr *MockClientMockRecorder) Complete(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockClient)(nil).Complete), ctx, req)
}

// GetAutoCompactTokenLimit mocks base method.
func (m *MockClient) GetAutoCompactTokenLimit() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAutoCompactTokenLimit")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetAutoCompactTokenLimit indicates an expected call of GetAutoCompactTokenLimit.
func (mr *MockClientMockRecorder) GetAutoCompactTokenLimit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAutoCompactTokenLimit", reflect.TypeOf((*MockClient)(nil).GetAutoCompactTokenLimit))
}

// GetModelContextWindow mocks base method.
func (m *MockClient) GetModelContextWindow() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelContextWindow")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetModelContextWindow indicates an expected call of GetModelContextWindow.
func (mr *MockClientMockRecorder) GetModelContextWindow() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelContextWindow", reflect.TypeOf((*MockClient)(nil).GetModelContextWindow))
}

// Stream mocks base method.
func (m *MockClient) Stream(ctx context.Context, req *client.ChatCompletionRequest) (<-chan client.StreamEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stream", ctx, req)
	ret0, _ := ret[0].(<-chan client.StreamEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stream indicates an expected call of Stream.
func (mr *MockClientMockRecorder) Stream(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stream", reflect.TypeOf((*MockClient)(nil).Stream), ctx, req)
}

// MockHTTPClient is a mock of HTTPClient interface.
type MockHTTPClient struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPClientMockRecorder
	isgomock struct{}
}

// MockHTTPClientMockRecorder is the mock recorder for MockHTTPClient.
type MockHTTPClientMockRecorder struct {
	mock *MockHTTPClient
}

// NewMockHTTPClient creates a new mock instance.
func NewMockHTTPClient(ctrl *gomock.Controller) *MockHTTPClient {
	mock := &MockHTTPClient{ctrl: ctrl}
	mock.recorder = &MockHTTPClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPClient) EXPECT() *MockHTTPClientMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockHTTPClient) Do(req *client.HTTPRequest) (*client.HTTPResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", req)
	ret0, _ := ret[0].(*client.HTTPResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockHTTPClientMockRecorder) Do(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockHTTPClient)(nil).Do), req)
}
